### ISSUE TITLE
UI of the category removal is inconsistent

### ISSUE THREAD

**Issue by gfcittolin** [DiegoRampim/node-red-dashboard#7]
The UI of the category removal dialog is a bit inconsistent:

![image](https://user-images.githubusercontent.com/2856088/34849811-d29f6fe2-f70a-11e7-920d-498f8171d57a.png)

- There are two "primary" buttons (red background)
- The "Remove" button has a brown text color, looking like it's disabled, even though it's not

(For reference, here's how the "flow changed" dialog is presented)
![image](https://user-images.githubusercontent.com/2856088/34850021-7c869cba-f70b-11e7-815b-5f55e98faa22.png)

**Comment by DiegoRampim** [comment]
![image](https://user-images.githubusercontent.com/13188136/34940096-6f39379e-f9d5-11e7-9efd-bfca6caaea70.png)
